<a href="https://colab.research.google.com/github/Neermita18/Deep-Learning/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Backpropagation with user functions


In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
X= torch.rand(2,3)
Y= torch.rand(2,1)
W= torch.zeros(3,1)

In [37]:
def forward(x):
  return torch.from_numpy(np.dot(x,W))
def loss(y,y_pred):
  return ((y_pred-y)**2).mean()
def gradient(x,y,y_pred):
  return np.dot(2*x.T,y_pred-y).mean()

> Basic Backprop and Loss

In [38]:
lr=0.01
i=10
for epoch in range(i):
  y_pred=forward(X)
  l=loss(Y,y_pred)
  dw=gradient(X,Y,y_pred)
  W-=lr*dw
  print(f"Loss: {l}\n")

Loss: 0.2717524766921997

Loss: 0.2552673816680908

Loss: 0.24013637006282806

Loss: 0.22624818980693817

Loss: 0.21350081264972687

Loss: 0.20180046558380127

Loss: 0.19106118381023407

Loss: 0.18120403587818146

Loss: 0.17215652763843536

Loss: 0.16385219991207123



### Backprop with Autograd

In [39]:
X=torch.rand(2,3, dtype=torch.float32)
Y=torch.rand(2,1,dtype=torch.float32)
W=torch.zeros(3,1,dtype=torch.float32,requires_grad=True)

In [40]:
def forward(x):
  return torch.matmul(x,W)
def loss(y,y_pred):
  return ((y_pred-y)**2).mean()
def gradient(x,y,y_pred):
  return np.dot(2*x.T,y_pred-y).mean()

In [41]:
epochs=500
lr=0.01
for epoch in range(epochs):
  y_pred=forward(X)
  l=loss(Y,y_pred)
  l.backward()
  with torch.no_grad():
    W-=lr*W.grad #manual updation of weights
  W.grad.zero_()
  if epoch%10==0:
    print(f"Loss: {l}")

Loss: 0.36088237166404724
Loss: 0.2830577790737152
Loss: 0.22662831842899323
Loss: 0.18559259176254272
Loss: 0.15563520789146423
Loss: 0.13365286588668823
Loss: 0.11741384118795395
Loss: 0.10531329363584518
Loss: 0.0961969643831253
Loss: 0.08923481404781342
Loss: 0.08382968604564667
Loss: 0.07955212891101837
Loss: 0.07609312236309052
Loss: 0.07323035597801208
Loss: 0.07080376148223877
Loss: 0.06869816780090332
Loss: 0.06683050096035004
Loss: 0.0651409775018692
Loss: 0.06358647346496582
Loss: 0.06213575601577759
Loss: 0.06076633930206299
Loss: 0.059461817145347595
Loss: 0.0582103431224823
Loss: 0.05700325220823288
Loss: 0.055834174156188965
Loss: 0.05469841510057449
Loss: 0.05359248071908951
Loss: 0.052513740956783295
Loss: 0.051460184156894684
Loss: 0.05043027177453041
Loss: 0.04942277818918228
Loss: 0.048436716198921204
Loss: 0.047471240162849426
Loss: 0.046525683254003525
Loss: 0.045599453151226044
Loss: 0.044691987335681915
Loss: 0.04380284249782562
Loss: 0.042931556701660156
Loss: 

### PyTorch functions

In [42]:
import torch.nn as nn

In [43]:
X=torch.rand(2,3, dtype=torch.float32)
Y=torch.rand(2,1,dtype=torch.float32)
W=torch.zeros(3,1,dtype=torch.float32,requires_grad=True)

In [45]:
def forward(x):
  return torch.matmul(x,W)


In [46]:
loss= nn.MSELoss()
optimizer= torch.optim.SGD([W],lr=0.01)

In [47]:
epochs=100
for epoch in range(epochs):
  y_pred=forward(X)
  l=loss(Y,y_pred)
  l.backward()
  optimizer.step() #automatic update weights
  optimizer.zero_grad()
  print(f"Epoch: {epoch}, Loss: {l}")

Epoch: 0, Loss: 0.28995728492736816
Epoch: 1, Loss: 0.2840479910373688
Epoch: 2, Loss: 0.2782595157623291
Epoch: 3, Loss: 0.27258944511413574
Epoch: 4, Loss: 0.2670353353023529
Epoch: 5, Loss: 0.2615947723388672
Epoch: 6, Loss: 0.2562655210494995
Epoch: 7, Loss: 0.25104519724845886
Epoch: 8, Loss: 0.24593167006969452
Epoch: 9, Loss: 0.2409226894378662
Epoch: 10, Loss: 0.2360161542892456
Epoch: 11, Loss: 0.23120993375778198
Epoch: 12, Loss: 0.22650201618671417
Epoch: 13, Loss: 0.22189034521579742
Epoch: 14, Loss: 0.21737302839756012
Epoch: 15, Loss: 0.2129480391740799
Epoch: 16, Loss: 0.2086135298013687
Epoch: 17, Loss: 0.20436766743659973
Epoch: 18, Loss: 0.2002086043357849
Epoch: 19, Loss: 0.19613458216190338
Epoch: 20, Loss: 0.19214388728141785
Epoch: 21, Loss: 0.18823476135730743
Epoch: 22, Loss: 0.1844055950641632
Epoch: 23, Loss: 0.18065470457077026
Epoch: 24, Loss: 0.17698049545288086
Epoch: 25, Loss: 0.17338141798973083
Epoch: 26, Loss: 0.16985593736171722
Epoch: 27, Loss: 0.166

### Without manual weights and forward

In [48]:
model=nn.Linear(3,3)

In [49]:
epochs=100
lr=0.01
loss= nn.MSELoss()
optimizer= torch.optim.SGD(model.parameters(),lr=0.01)

In [50]:
for epoch in range(epochs):
  y_pred=model(X)
  l=loss(Y,y_pred)
  l.backward()
  optimizer.step() #automatic update weights
  optimizer.zero_grad()
  print(f"Epoch: {epoch}, Loss: {l}")

Epoch: 0, Loss: 0.40170636773109436
Epoch: 1, Loss: 0.3939256966114044
Epoch: 2, Loss: 0.38630053400993347
Epoch: 3, Loss: 0.3788280487060547
Epoch: 4, Loss: 0.37150493264198303
Epoch: 5, Loss: 0.3643285036087036
Epoch: 6, Loss: 0.35729551315307617
Epoch: 7, Loss: 0.35040321946144104
Epoch: 8, Loss: 0.34364888072013855
Epoch: 9, Loss: 0.3370295763015747
Epoch: 10, Loss: 0.3305427134037018
Epoch: 11, Loss: 0.3241855204105377
Epoch: 12, Loss: 0.31795555353164673
Epoch: 13, Loss: 0.3118501305580139
Epoch: 14, Loss: 0.3058668375015259
Epoch: 15, Loss: 0.30000320076942444
Epoch: 16, Loss: 0.2942568361759186
Epoch: 17, Loss: 0.2886253297328949
Epoch: 18, Loss: 0.2831064760684967
Epoch: 19, Loss: 0.27769798040390015
Epoch: 20, Loss: 0.27239760756492615
Epoch: 21, Loss: 0.267203152179718
Epoch: 22, Loss: 0.2621126174926758
Epoch: 23, Loss: 0.25712379813194275
Epoch: 24, Loss: 0.2522347867488861
Epoch: 25, Loss: 0.24744343757629395
Epoch: 26, Loss: 0.24274788796901703
Epoch: 27, Loss: 0.2381461

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([2, 3])) that is different to the input size (torch.Size([2, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [51]:
model

Linear(in_features=3, out_features=3, bias=True)

### Data Manipulation

In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

In [4]:
x= torch.arange(12, dtype=torch.float32)

In [5]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [7]:
x.numel()

12

In [16]:
x=x.reshape(-1,1)

In [17]:
x.shape

torch.Size([12, 1])

In [24]:
torch.rand(2,2)  #0 and 1

tensor([[0.0659, 0.8180],
        [0.2937, 0.8608]])

In [25]:
torch.randn(2,2) #gausssian distr

tensor([[-0.8421, -1.8728],
        [-0.5200, -0.3658]])

### Data Manipulation

In [2]:
X= torch.arange(12, dtype=torch.float32).reshape(3,4)
Y= torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

In [3]:
torch.cat((X,Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [4]:
torch.cat((X,Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [5]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [6]:
X.sum()

tensor(66.)

### Data Preparation

In [26]:
import os
os.makedirs(os.path.join("..", 'data'), exist_ok=True)
data_file= os.path.join("..", 'data', 'house_tiny.csv')
with open(data_file, 'w' ) as f:
  f.write('''NumRooms,Alley,Price
  NA,NA,127500
  2,NA,106000
  4,Slate,178637
  NA,NA,140000''')

In [44]:
data= pd.read_csv("/data/house_tiny.csv")

In [48]:
data

NumRooms  Alley   Price
0       NaN    NaN  127500
1       2.0    NaN  106000
2       4.0  Slate  178637
3       NaN    NaN  140000

convert all columns with numbers to numeric and then fill NA with mean.

In [47]:
data['NumRooms'] = pd.to_numeric(data['NumRooms'], errors='coerce')

In [49]:
X, y= data.iloc[:, 0:2], data.iloc[:, 2]

In [51]:
X= pd.get_dummies(X, dummy_na=True)

In [52]:
X= X.fillna(X.mean())

In [55]:
X

NumRooms  Alley_Slate  Alley_nan
0       3.0        False       True
1       2.0        False       True
2       4.0         True      False
3       3.0        False       True